import type { AIOperation, AIProviderKind } from "@/generated/prisma/enums";
import type { AiErrorKind } from "./errors";

/**
 * The orchestration boundary.
 *
 * Nothing outside `src/server/ai/orchestration` may call a model. Routes,
 * components, strategy services, the content director and workers all call
 * `runAiOperation`, which is the only thing that speaks to a `ModelProvider`.
 *
 * A provider declares what kind of thing it is. That declaration is carried all
 * the way to the UI, so a deterministic result can never be read as model
 * output — see `provenanceLabel`.
 */

export type ModelUsage = {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
};

export const ZERO_USAGE: ModelUsage = {
  inputTokens: 0,
  outputTokens: 0,
  cacheReadTokens: 0,
  cacheWriteTokens: 0,
};

export type ModelRequest = {
  operation: AIOperation;
  promptName: string;
  promptVersion: string;
  system: string;
  user: string;
  maxOutputTokens: number;
  /** JSON Schema the output must satisfy. Providers may enforce it natively. */
  jsonSchema: Record<string, unknown>;
  /**
   * The typed input, for providers that compute an answer rather than generate
   * one. A generating provider must ignore this and work from the rendered text.
   */
  input: unknown;
  /**
   * The prompt's deterministic implementation, when it has one. Present only so
   * the deterministic provider can serve the operation; an LLM provider must
   * never call it, because doing so would let rule output be labelled as model
   * output.
   */
  computeDeterministic?: (input: unknown) => unknown | Promise<unknown>;
  /** Set when asking a provider to correct its own schema-invalid output. */
  repair?: {
    previousOutput: string;
    problems: string[];
  };
};

export type ModelResponse = {
  /** Raw text as produced. Parsed and validated by the runner, never trusted. */
  text: string;
  usage: ModelUsage;
  /** Priced from the provider's own table at call time. */
  costUsd: number;
  /** True when the model had a published price. False means cost is a floor. */
  priced: boolean;
  model: string | null;
};

export type ProviderAvailability =
  | { available: true }
  | { available: false; reason: string };

export interface ModelProvider {
  readonly name: string;
  /**
   * DETERMINISTIC or LLM. Load-bearing: it is written to the job record and
   * shown to operators. A provider that generates text must never claim
   * DETERMINISTIC, and a provider that applies rules must never claim LLM.
   */
  readonly kind: AIProviderKind;
  /** Null for deterministic providers, which have no model. */
  readonly model: string | null;
  /** Whether this provider can serve a request right now, and if not, why. */
  availability(): ProviderAvailability;
  /** Whether it can serve this particular request. */
  canServe(request: ModelRequest): boolean;
  complete(request: ModelRequest): Promise<ModelResponse>;
}

/** Where a result came from. Travels with every result to the UI. */
export type AiProvenance = {
  providerName: string;
  providerKind: AIProviderKind;
  model: string | null;
  promptName: string;
  promptVersion: string;
  /** True when no language model was involved. */
  deterministic: boolean;
};

/**
 * The sentence the UI shows above an AI result. Derived from provenance rather
 * than written by hand at each call site, so a deterministic result is always
 * described as one.
 */
export function provenanceLabel(provenance: AiProvenance): string {
  if (provenance.deterministic) {
    return `Generated by rules (${provenance.providerName}, ${provenance.promptName} v${provenance.promptVersion}) — no language model was used.`;
  }
  return `Generated by ${provenance.model ?? provenance.providerName} (${provenance.promptName} v${provenance.promptVersion}).`;
}

export type AiJobSummary = {
  id: string;
  operation: AIOperation;
  provenance: AiProvenance;
  attempts: number;
  repairAttempts: number;
  usage: ModelUsage;
  costUsd: number;
  latencyMs: number;
};

/**
 * A discriminated union rather than a throw, so a caller has to acknowledge the
 * failure case. Every branch still carries the job summary — a failed job cost
 * money and must show up in cost accounting.
 */
export type AiResult<T> =
  | { ok: true; value: T; job: AiJobSummary }
  | { ok: false; errorKind: AiErrorKind; message: string; job: AiJobSummary };
