import { readFile } from "node:fs/promises";
import { glob } from "node:fs/promises";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import { z } from "zod";
import { prisma } from "@/server/db";
import { AIJobStatus, AIOperation, AIProviderKind } from "@/generated/prisma/enums";
import {
  aiSpend,
  aiSpendByOperation,
  ANTHROPIC_PRICING,
  anthropicProvider,
  assetAnalysisPrompt,
  copyVariantsPrompt,
  deterministicProvider,
  hashInput,
  hashPrompt,
  listPrompts,
  priceUsage,
  provenanceLabel,
  registerPrompt,
  runAiOperation,
  type ModelProvider,
  type ModelRequest,
  type ModelResponse,
} from "@/server/ai/orchestration";
import { extractJson, validateOutput } from "@/server/ai/orchestration/validate";
import { AiError } from "@/server/ai/orchestration/errors";
import { ensureWorkspace, migrateTestSchema, resetDatabase } from "./helpers";

/**
 * Phase 2: the AI orchestration boundary.
 *
 * The properties under test are the ones that would let the system lie:
 * deterministic output presented as model output, invalid output stored as a
 * result, repair attempts that cost money without appearing in the bill, and a
 * missing API key silently becoming a fabricated answer.
 */

// A schema small enough to make failure modes obvious.
const echoSchema = z.object({
  value: z.string().min(1),
  n: z.number().int().min(0),
});
type EchoOutput = z.infer<typeof echoSchema>;
type EchoInput = { value: string; n: number };

const echoPrompt = registerPrompt<EchoInput, EchoOutput>({
  name: "test-echo",
  version: "1.0.0",
  operation: AIOperation.HOOK_REWRITE,
  description: "Test fixture prompt.",
  schema: echoSchema,
  maxOutputTokens: 200,
  render: (input) => ({ system: "echo", user: JSON.stringify(input) }),
  deterministic: (input) => ({ value: input.value, n: input.n }),
  refine: (value) =>
    value.value === "forbidden" ? ['value: "forbidden" is not allowed.'] : [],
});

/** A stub LLM whose scripted responses drive the repair and retry paths. */
function stubProvider(
  script: Array<ModelResponse | Error>,
  overrides: Partial<Pick<ModelProvider, "name" | "kind" | "model">> = {},
): ModelProvider & { calls: ModelRequest[] } {
  const calls: ModelRequest[] = [];
  let index = 0;
  return {
    name: overrides.name ?? "stub-llm",
    kind: overrides.kind ?? AIProviderKind.LLM,
    model: overrides.model ?? "stub-model-1",
    calls,
    availability: () => ({ available: true }),
    canServe: () => true,
    async complete(request) {
      calls.push(request);
      const next = script[Math.min(index, script.length - 1)];
      index += 1;
      if (next instanceof Error) throw next;
      return next!;
    },
  };
}

function response(text: string, over: Partial<ModelResponse> = {}): ModelResponse {
  return {
    text,
    usage: { inputTokens: 1_000, outputTokens: 200, cacheReadTokens: 0, cacheWriteTokens: 0 },
    costUsd: 0.01,
    priced: true,
    model: "stub-model-1",
    ...over,
  };
}

let workspaceId: string;

beforeAll(async () => {
  await migrateTestSchema();
});

beforeEach(async () => {
  await resetDatabase();
  workspaceId = (await ensureWorkspace()).id;
});

describe("provider honesty", () => {
  it("labels the deterministic provider as deterministic and gives it no model", async () => {
    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "hello", n: 1 },
      workspaceId,
    });

    expect(result.ok).toBe(true);
    expect(result.job.provenance.providerKind).toBe(AIProviderKind.DETERMINISTIC);
    expect(result.job.provenance.deterministic).toBe(true);
    expect(result.job.provenance.model).toBeNull();
    expect(provenanceLabel(result.job.provenance)).toContain(
      "no language model was used",
    );
    expect(provenanceLabel(result.job.provenance)).not.toMatch(/claude|gpt|llm/i);

    const job = await prisma.aIJob.findUniqueOrThrow({ where: { id: result.job.id } });
    expect(job.providerKind).toBe(AIProviderKind.DETERMINISTIC);
    expect(job.model).toBeNull();
    expect(job.costUsd).toBe(0);
  });

  it("never lets a rule-based result be labelled as model output", async () => {
    // The claim comes from the provider's declared kind, not from its name or
    // from whether a model string happens to be set.
    expect(deterministicProvider.kind).toBe(AIProviderKind.DETERMINISTIC);
    expect(deterministicProvider.model).toBeNull();

    const label = provenanceLabel({
      providerName: deterministicProvider.name,
      providerKind: deterministicProvider.kind,
      model: null,
      promptName: "test-echo",
      promptVersion: "1.0.0",
      deterministic: true,
    });
    expect(label).toContain("Generated by rules");
  });

  it("keeps the Anthropic provider inactive without a key, and says why", () => {
    const availability = anthropicProvider.availability();
    expect(availability.available).toBe(false);
    if (!availability.available) {
      expect(availability.reason).toContain("ANTHROPIC_API_KEY");
    }
    expect(anthropicProvider.kind).toBe(AIProviderKind.LLM);
  });

  it("records the unavailable model as an attempt rather than hiding the fallback", async () => {
    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "hello", n: 2 },
      workspaceId,
      // Exercise the real selection path in "auto" mode with no key present.
      provider: undefined,
    });

    expect(result.ok).toBe(true);
    expect(result.job.provenance.deterministic).toBe(true);
  });
});

describe("schema validation and repair", () => {
  it("rejects output that does not satisfy the schema and repairs it", async () => {
    const provider = stubProvider([
      response(JSON.stringify({ value: "", n: "not a number" })),
      response(JSON.stringify({ value: "fixed", n: 3 })),
    ]);

    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "ignored", n: 0 },
      workspaceId,
      provider,
    });

    expect(result.ok).toBe(true);
    if (result.ok) expect(result.value).toEqual({ value: "fixed", n: 3 });
    expect(result.job.attempts).toBe(2);
    expect(result.job.repairAttempts).toBe(1);

    // The repair turn must name the actual problems, not just retry blindly.
    expect(provider.calls[1]?.repair).toBeDefined();
    expect(provider.calls[1]?.repair?.problems.join(" ")).toContain("n:");

    const job = await prisma.aIJob.findUniqueOrThrow({ where: { id: result.job.id } });
    expect(job.status).toBe(AIJobStatus.SUCCEEDED);
    expect((job.validationErrors as unknown[]).length).toBe(1);
  });

  it("gives up after the repair budget and never returns unvalidated output", async () => {
    const provider = stubProvider([response(JSON.stringify({ nope: true }))]);

    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 0 },
      workspaceId,
      provider,
      maxRepairs: 2,
    });

    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.errorKind).toBe("INVALID_OUTPUT");
    expect(result.job.attempts).toBe(3);
    expect(result.job.repairAttempts).toBe(2);

    const job = await prisma.aIJob.findUniqueOrThrow({ where: { id: result.job.id } });
    expect(job.status).toBe(AIJobStatus.INVALID_OUTPUT);
    // Nothing unvalidated is ever written to output.
    expect(job.output).toBeNull();
  });

  it("treats a broken brand rule as something to repair, not something to ship", async () => {
    const provider = stubProvider([
      response(JSON.stringify({ value: "forbidden", n: 1 })),
      response(JSON.stringify({ value: "allowed", n: 1 })),
    ]);

    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 1 },
      workspaceId,
      provider,
    });

    expect(result.ok).toBe(true);
    if (result.ok) expect(result.value.value).toBe("allowed");
    expect(provider.calls[1]?.repair?.problems[0]).toContain("forbidden");
  });

  it("recovers JSON from fenced or padded responses without spending a repair", async () => {
    const provider = stubProvider([
      response('Here you go:\n```json\n{"value":"ok","n":7}\n```\nHope that helps.'),
    ]);

    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 7 },
      workspaceId,
      provider,
    });

    expect(result.ok).toBe(true);
    expect(result.job.repairAttempts).toBe(0);
  });

  it("refuses to repair a deterministic provider's own bad output", async () => {
    const brokenPrompt = registerPrompt<EchoInput, EchoOutput>({
      name: "test-broken-rules",
      version: "1.0.0",
      operation: AIOperation.HOOK_REWRITE,
      description: "A deterministic implementation that violates its own contract.",
      schema: echoSchema,
      maxOutputTokens: 200,
      render: () => ({ system: "s", user: "u" }),
      // Deliberately out of contract: n must be a number.
      deterministic: () => ({ value: "x", n: "no" } as unknown as EchoOutput),
    });

    const result = await runAiOperation({
      prompt: brokenPrompt,
      input: { value: "x", n: 0 },
      workspaceId,
      provider: deterministicProvider,
    });

    expect(result.ok).toBe(false);
    // Attempt 1 produced invalid output; the repair attempt is refused by the
    // provider, so the job fails fast rather than looping over a bug.
    if (!result.ok) expect(result.errorKind).toBe("INVALID_OUTPUT");
  });
});

describe("retry and failure classification", () => {
  it("retries a retryable provider failure and records every attempt", async () => {
    const provider = stubProvider([
      new AiError("OVERLOADED", "upstream is overloaded"),
      new AiError("OVERLOADED", "upstream is overloaded"),
      response(JSON.stringify({ value: "eventually", n: 1 })),
    ]);

    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 1 },
      workspaceId,
      provider,
      maxRetries: 2,
    });

    expect(result.ok).toBe(true);
    expect(result.job.attempts).toBe(3);

    const usage = await prisma.aIUsageLog.findMany({
      where: { aiJobId: result.job.id },
      orderBy: { attempt: "asc" },
    });
    expect(usage.map((row) => row.ok)).toEqual([false, false, true]);
    expect(usage[0]?.errorKind).toBe("OVERLOADED");
  });

  it("does not retry a non-retryable failure", async () => {
    const provider = stubProvider([new AiError("AUTH", "invalid api key")]);

    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 1 },
      workspaceId,
      provider,
      maxRetries: 3,
    });

    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.errorKind).toBe("AUTH");
    expect(result.job.attempts).toBe(1);

    const job = await prisma.aIJob.findUniqueOrThrow({ where: { id: result.job.id } });
    expect(job.status).toBe(AIJobStatus.FAILED);
  });

  it("never stores a credential that leaked into an error message", async () => {
    const provider = stubProvider([
      new AiError("BAD_REQUEST", "rejected request with x-api-key: sk-ant-secret-value-123"),
    ]);

    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 1 },
      workspaceId,
      provider,
    });

    const job = await prisma.aIJob.findUniqueOrThrow({ where: { id: result.job.id } });
    expect(job.error).not.toContain("sk-ant-secret-value-123");
    expect(job.error).toContain("***");
    if (!result.ok) expect(result.message).not.toContain("sk-ant-secret-value-123");
  });
});

describe("cost and latency accounting", () => {
  it("prices Anthropic usage from the published table", () => {
    const priced = priceUsage("claude-opus-5", {
      inputTokens: 1_000_000,
      outputTokens: 100_000,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
    });
    // $5 per 1M input + $25 per 1M output x 0.1M = $5 + $2.50
    expect(priced.usd).toBeCloseTo(7.5, 6);
    expect(priced.priced).toBe(true);
    expect(ANTHROPIC_PRICING["claude-opus-5"]?.inputPerMTok).toBe(5);
  });

  it("flags an unknown model rather than inventing a price", () => {
    const priced = priceUsage("some-future-model", {
      inputTokens: 10_000,
      outputTokens: 1_000,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
    });
    expect(priced.priced).toBe(false);
    expect(priced.usd).toBe(0);
  });

  it("bills every attempt, including repairs", async () => {
    const provider = stubProvider([
      response(JSON.stringify({ bad: true })),
      response(JSON.stringify({ value: "ok", n: 1 })),
    ]);

    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 1 },
      workspaceId,
      provider,
    });

    expect(result.ok).toBe(true);
    // Two calls at $0.01 each — the repair is not free and is not hidden.
    expect(result.job.costUsd).toBeCloseTo(0.02, 6);
    expect(result.job.usage.inputTokens).toBe(2_000);

    const spend = await aiSpend({ workspaceId });
    expect(spend.jobs).toBe(1);
    expect(spend.attempts).toBe(2);
    expect(spend.repairAttempts).toBe(1);
    expect(spend.costUsd).toBeCloseTo(0.02, 6);
  });

  it("counts a failed job's spend too", async () => {
    const provider = stubProvider([response("not json at all")]);

    await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 1 },
      workspaceId,
      provider,
      maxRepairs: 1,
    });

    const spend = await aiSpend({ workspaceId });
    expect(spend.attempts).toBe(2);
    expect(spend.costUsd).toBeGreaterThan(0);

    const byOperation = await aiSpendByOperation({ workspaceId });
    expect(byOperation[0]?.operation).toBe(AIOperation.HOOK_REWRITE);
    expect(byOperation[0]?.failureRate).toBe(1);
  });

  it("records latency per attempt from a controllable clock", async () => {
    let now = 1_000;
    const clock = () => (now += 250);

    const provider = stubProvider([response(JSON.stringify({ value: "ok", n: 1 }))]);
    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "x", n: 1 },
      workspaceId,
      provider,
      clock,
    });

    expect(result.job.latencyMs).toBeGreaterThan(0);
    const usage = await prisma.aIUsageLog.findFirstOrThrow({
      where: { aiJobId: result.job.id },
    });
    expect(usage.latencyMs).toBe(250);
  });
});

describe("the persisted record", () => {
  it("stores the prompt version and hashes so history stays attributable", async () => {
    const result = await runAiOperation({
      prompt: echoPrompt,
      input: { value: "hello", n: 4 },
      workspaceId,
    });

    const job = await prisma.aIJob.findUniqueOrThrow({ where: { id: result.job.id } });
    expect(job.promptName).toBe("test-echo");
    expect(job.promptVersion).toBe("1.0.0");
    expect(job.promptHash).toBe(hashPrompt(echoPrompt.render({ value: "hello", n: 4 })));
    expect(job.inputHash).toBe(hashInput({ value: "hello", n: 4 }));
  });

  it("hashes inputs independently of key order", () => {
    expect(hashInput({ a: 1, b: 2 })).toBe(hashInput({ b: 2, a: 1 }));
    expect(hashInput({ a: 1 })).not.toBe(hashInput({ a: 2 }));
  });

  it("refuses to register the same prompt name and version twice", () => {
    expect(() =>
      registerPrompt({
        name: "test-echo",
        version: "1.0.0",
        operation: AIOperation.HOOK_REWRITE,
        description: "duplicate",
        schema: echoSchema,
        maxOutputTokens: 10,
        render: () => ({ system: "", user: "" }),
        deterministic: () => ({ value: "x", n: 0 }),
      }),
    ).toThrow(/Bump the version/);
  });
});

describe("registered prompts", () => {
  it("gives every registered prompt a deterministic implementation", () => {
    const prompts = listPrompts();
    expect(prompts.length).toBeGreaterThan(0);
    for (const prompt of prompts) {
      expect(typeof prompt.deterministic).toBe("function");
    }
  });

  it("produces schema-valid analysis from rules alone, admitting what it cannot know", async () => {
    const result = await runAiOperation({
      prompt: assetAnalysisPrompt,
      input: {
        asset: {
          title: "Dashboard tutorial",
          originalFilename: "app-tutorial-walkthrough.mp4",
          kind: "VIDEO",
          durationSeconds: 32,
          width: 1080,
          height: 1920,
          aspectRatio: "9:16",
          hasAudio: true,
          pillar: "core",
        },
        brand: brandContext(),
      },
      workspaceId,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    // A filename is a weak signal and the rules do not borrow confidence from
    // the fact that a computer produced the answer.
    expect(result.value.confidence).toBe("LOW");
    expect(result.value.basis.length).toBeGreaterThan(0);
    expect(result.value.unknowns.join(" ")).toContain("media itself");
  });

  it("writes brand-safe copy variants from rules alone", async () => {
    const result = await runAiOperation({
      prompt: copyVariantsPrompt,
      input: {
        asset: {
          title: "Build log day 4",
          originalFilename: "build-in-public-day-4.mp4",
          kind: "VIDEO",
          durationSeconds: 21,
          width: 1080,
          height: 1920,
          aspectRatio: "9:16",
          hasAudio: true,
          pillar: "core",
        },
        brand: brandContext(),
        analysis: {
          format: "BUILD_IN_PUBLIC",
          topic: "shipping a feature",
          likelyAudience: "indie builders",
          visualSummary: null,
          transcript: null,
          raw: {},
        },
        count: 3,
      },
      workspaceId,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.variants).toHaveLength(3);
    const text = result.value.variants
      .map((variant) => `${variant.hook} ${variant.caption}`)
      .join(" ")
      .toLowerCase();
    expect(text).not.toContain("guaranteed");
    // No variant may claim a result — that is the learning engine's territory.
    expect(text).not.toMatch(/will go viral|guaranteed views/);
  });
});

describe("the boundary holds", () => {
  it("keeps the Anthropic SDK inside the provider module", async () => {
    const offenders: string[] = [];
    for await (const file of glob("src/**/*.{ts,tsx}")) {
      const path = file.replace(/\\/g, "/");
      if (path.endsWith("src/server/ai/orchestration/providers/anthropic.ts")) continue;
      const source = await readFile(file, "utf8");
      if (source.includes("@anthropic-ai/sdk")) offenders.push(path);
    }
    expect(offenders).toEqual([]);
  });

  it("keeps ANTHROPIC_API_KEY reads inside env.ts", async () => {
    const offenders: string[] = [];
    for await (const file of glob("src/**/*.{ts,tsx}")) {
      const path = file.replace(/\\/g, "/");
      if (path.endsWith("src/env.ts")) continue;
      const source = await readFile(file, "utf8");
      if (source.includes("ANTHROPIC_API_KEY") && source.includes("process.env")) {
        offenders.push(path);
      }
    }
    expect(offenders).toEqual([]);
  });
});

describe("parsing untrusted output", () => {
  it("extracts JSON from bare, fenced and padded text", () => {
    expect(extractJson('{"a":1}')).toEqual({ a: 1 });
    expect(extractJson('```json\n{"a":1}\n```')).toEqual({ a: 1 });
    expect(extractJson('Sure!\n{"a":1}\nDone.')).toEqual({ a: 1 });
  });

  it("reports precise problems rather than a generic failure", () => {
    const outcome = validateOutput(echoSchema, '{"value":"", "n":-1}');
    expect(outcome.ok).toBe(false);
    if (!outcome.ok) {
      expect(outcome.problems.join(" ")).toContain("value");
      expect(outcome.problems.join(" ")).toContain("n");
    }
  });

  it("does not evaluate what it parses", () => {
    // Parsed, never evaluated: a payload that would be dangerous to execute is
    // just data, and fails validation like any other wrong shape.
    const outcome = validateOutput(echoSchema, '{"value":"__proto__","n":0,"toString":"x"}');
    expect(outcome.ok).toBe(true);
    expect(Object.prototype.toString).toBe(Object.prototype.toString);
  });
});

function brandContext() {
  return {
    projectName: "Test Project",
    audience: "indie builders",
    tone: "plain",
    valueProp: "It does the thing.",
    primaryCta: "Link in bio",
    website: null,
    bannedPhrases: ["guaranteed", "get rich"],
    pillars: ["core"],
    knownHashtags: ["#testing"],
  };
}
